# Generated by Django 5.2.5 on 2025-08-27 12:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField()),
                ("image_url", models.URLField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="categories.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="products_pr_name_9ff0a3_idx"),
                    models.Index(fields=["price"], name="products_pr_price_9b1a5f_idx"),
                    models.Index(
                        fields=["stock_quantity"], name="products_pr_stock_q_ba97b5_idx"
                    ),
                    models.Index(
                        fields=["category"], name="products_pr_categor_9edb3d_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="products_pr_created_f0feec_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", Decimal("0.01"))),
                        name="price_gte_0_01",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stock_quantity__gte", 0)),
                        name="stock_qty_gte_0",
                    ),
                ],
            },
        ),
    ]
